# Generated by Django 2.2.2 on 2019-06-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hawker',
            fields=[
                ('hawker_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hawker_name', models.CharField(default='', max_length=50)),
                ('hawker_mobile', models.CharField(default='', max_length=40)),
                ('hawker_address', models.CharField(default='', max_length=50)),
                ('hawker_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('customer_mobile', models.CharField(default='', max_length=40)),
                ('customer_email', models.CharField(default='', max_length=40)),
                ('customer_address', models.CharField(default='', max_length=50)),
                ('customer_date', models.DateTimeField(blank=True, null=True)),
                ('hawker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Hawker', verbose_name='hawker')),
            ],
        ),
    ]
