# Generated by Django 2.2.2 on 2019-06-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Group',
            fields=[
                ('fee_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fee_sr', models.CharField(default=0, max_length=50)),
                ('fee_date', models.DateTimeField(blank=True, null=True)),
                ('fee_description', models.CharField(default='', max_length=40)),
                ('fee_month', models.CharField(default='', max_length=40)),
                ('fee_amount', models.IntegerField(default=0)),
                ('fee_paid', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Customer', verbose_name='customer')),
            ],
            options={
                'verbose_name_plural': 'Fee Group',
            },
        ),
    ]
