# Generated by Django 2.2.2 on 2019-06-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_fee_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fee_Group',
            new_name='Invoice',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'invoice'},
        ),
    ]
