# Generated by Django 2.2.2 on 2019-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190626_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeMaster',
            fields=[
                ('fee_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fee_due_date', models.DateTimeField(blank=True, null=True)),
                ('fee_month', models.CharField(default='', max_length=40)),
                ('fee_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'fee master',
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
