# Generated by Django 2.2.2 on 2019-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190626_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('i_sr', models.CharField(default='', max_length=40)),
                ('i_date', models.DateTimeField(blank=True, null=True)),
                ('i_month', models.CharField(default='', max_length=40)),
                ('i_amount', models.IntegerField(default=0)),
                ('i_status', models.CharField(default='', max_length=40)),
                ('i_paid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'invoice',
            },
        ),
        migrations.DeleteModel(
            name='FeeMaster',
        ),
    ]
