# Generated by Django 2.2.2 on 2019-06-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190626_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Customer', verbose_name='customer'),
        ),
    ]
